---
title: "Cleaning_data"
author: "Andrei"
date: '2017 February 2 '
output: html_document
---

##The following codebook describes the data and the steps for the analysis


The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. See 'features_info.txt' for more details. 


#Data

##Identification:

* Subjects - Subjects participating in the study
* Activity - Activity measured during the study:

   *1 WALKING
   
   *2 WALKING_UPSTAIRS+
   
   *3 WALKING_DOWNSTAIRS
   
   *4 SITTING
   
   *5 STANDING
   
   *6 LAYING
   
##Variables

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

* tBodyAcc-XYZ

* tGravityAcc-XYZ

* tBodyAccJerk-XYZ
 
* tBodyGyro-XYZ

* tBodyGyroJerk-XYZ

* tBodyAccMag

* tGravityAccMag

* tBodyAccJerkMag

* tBodyGyroMag

* tBodyGyroJerkMag

* fBodyAcc-XYZ

* fBodyAccJerk-XYZ

* fBodyGyro-XYZ

* fBodyAccMag

* fBodyAccJerkMag

* fBodyGyroMag

* fBodyGyroJerkMag


Mean ans Standard Deviation:

* mean(): Mean value

* std(): Standard deviation



##Analysis - steps and resources

Libraries:

 - dplyr
 
 Steps
 
 0. Download data from the given URL
 1. Reading training and test data into R Studio
 2. Merging the data into a master dataset 
 3. Subsetting the mean and standard deviation measurments
 4. Labeling / nameing the activities and variables
 5. Subsetting a tidy dataset based on mean and standard deviation
 
 The Repo contains (among others) the .txt file of the tidy dataset.
 
 
 
